// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZdKHKep4ia8arg0uHe4qJZDDAKJtRtmI',
    appId: '1:306156501020:web:88ebeebebfe112737d47d9',
    messagingSenderId: '306156501020',
    projectId: 'proyecto1-548ee',
    authDomain: 'proyecto1-548ee.firebaseapp.com',
    storageBucket: 'proyecto1-548ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4c7aoA8dFq4_xtkgLcXzBpllR-PsyHUk',
    appId: '1:306156501020:android:a885f0a2002f77067d47d9',
    messagingSenderId: '306156501020',
    projectId: 'proyecto1-548ee',
    storageBucket: 'proyecto1-548ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk7xmdfDQvv_O5EtVlHoE_hQBLgehnVPY',
    appId: '1:306156501020:ios:0523c671f6deba137d47d9',
    messagingSenderId: '306156501020',
    projectId: 'proyecto1-548ee',
    storageBucket: 'proyecto1-548ee.appspot.com',
    iosClientId: '306156501020-a3jick70htd9vi08gqh5ehenh4fiet3p.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto117401034',
  );
}
